version: '3.3'
services:
    nginx:
        container_name: nginx
        build:
          context: ./nginx
          dockerfile: Dockerfile
        depends_on:
            - mongodb
        volumes:
            - ./static/:/static/
        ports:
            - "80:80"
        restart: always
    fast_api:
        image: fast_api
        container_name: fast_api
        depends_on:
            - nginx
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
