# Generated by Django 3.2.9 on 2021-11-20 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('name', models.CharField(max_length=50, verbose_name='Название Статьи')),
                ('discription', models.CharField(max_length=100, verbose_name='Описание')),
                ('data', models.DateField(auto_now_add=True, verbose_name='Дата публикации')),
                ('author', models.CharField(max_length=20, verbose_name='Автор')),
                ('blog_url', models.URLField(unique=True, verbose_name='Ссылка на статью')),
            ],
            options={
                'verbose_name_plural': 'Статьи блога',
            },
        ),
        migrations.CreateModel(
            name='Destinations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('discription', models.CharField(max_length=100, verbose_name='Описание')),
            ],
            options={
                'verbose_name_plural': 'Места назначения',
            },
        ),
    ]
