# Generated by Django 3.2.9 on 2021-11-20 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_userdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='phone_number',
            field=models.IntegerField(verbose_name='Телефон'),
        ),
    ]
