# Generated by Django 3.2.9 on 2021-11-20 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_userdata_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='phone_number',
            field=models.PositiveBigIntegerField(verbose_name='Телефон'),
        ),
    ]
