# Generated by Django 3.2.9 on 2021-11-20 15:44

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_userdata_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True),
        ),
    ]
