# Generated by Django 3.2.9 on 2021-11-21 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_userdata_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscirbe_Emails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50, verbose_name='Email')),
            ],
            options={
                'verbose_name_plural': 'Почты для рассылки',
            },
        ),
    ]
